# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/12196a9f-2d60-4b9e-b4d9-e7c79b369ced";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ad75fa71-4f8d-4ca9-8847-30d17b16f622".device = "/dev/disk/by-uuid/ad75fa71-4f8d-4ca9-8847-30d17b16f622";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B4F4-6111";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e4035bfd-7d50-4504-890c-f8586d32f48b"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


  # Specific setups
  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Use latest kernel.
  boot.initrd.luks.devices."luks-f0f99384-7fde-424a-8d40-0ba5f15a21a5".device = "/dev/disk/by-uuid/f0f99384-7fde-424a-8d40-0ba5f15a21a5";

  # Network
  networking.hostName = "nixos-dellp15-vivien"; # Define your hostname.
}
